
name: Release

on:
  push:
    branches:
      - master
      - development

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - uses: expo/expo-github-action@v5
      with:
        expo-version: 3.x
        expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
    - run: npm install
    - run: |
        if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
          expo publish --release-channel=production
        else
          expo publish --release-channel=staging
        fi
