# This is a basic workflow to help you get started with Actions

name: Test

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}

      - name: Install prerequisites
        run: npm install -g yarn

      - name: Install dev
        run: yarn install --dev

      - name: Launch tests
        run: yarn test

